// File: lib/firebase_options.dart
//
// ─────────────────────────────────────────────────────────────────────────────
// SETUP INSTRUCTIONS
// ─────────────────────────────────────────────────────────────────────────────
//
// This file is auto-generated by the FlutterFire CLI.
// Do NOT manually edit this file — regenerate it when your Firebase config changes.
//
// STEP 1: Install the FlutterFire CLI
//   dart pub global activate flutterfire_cli
//
// STEP 2: Connect your project to Firebase
//   flutterfire configure
//   → Select your Firebase project
//   → Select your target platforms (Android, iOS, Web, macOS)
//   → This generates `firebase_options.dart` automatically
//
// STEP 3: Enable Auth providers in Firebase Console
//   → Go to Firebase Console → Authentication → Sign-in method
//   → Enable: Email/Password
//   → Enable: Google
//
// STEP 4: For Android — add SHA-1 fingerprint
//   cd android && ./gradlew signingReport
//   → Copy the SHA-1 and add it in Firebase Console → Project Settings → Your app
//
// STEP 5: For iOS — add GoogleService-Info.plist
//   → Download from Firebase Console
//   → Add to Runner/GoogleService-Info.plist in Xcode
//
// ─────────────────────────────────────────────────────────────────────────────
// EXAMPLE (replace with your real values from `flutterfire configure`):
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️  Replace ALL values below with your actual Firebase project credentials.
  // Run `flutterfire configure` to generate this file automatically.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl4K-N5izYksBUpDtEX_MNvgefJCGHGHU',
    appId: '1:294025925697:web:8b467269b78a52b81a62c0',
    messagingSenderId: '294025925697',
    projectId: 'civictrack-b98b3',
    authDomain: 'civictrack-b98b3.firebaseapp.com',
    storageBucket: 'civictrack-b98b3.firebasestorage.app',
    measurementId: 'G-VFC37ELXW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBGNadpwElTAtiEgTyeZ2eR-qFV41lei8',
    appId: '1:294025925697:android:787d0e2b876e8d181a62c0',
    messagingSenderId: '294025925697',
    projectId: 'civictrack-b98b3',
    storageBucket: 'civictrack-b98b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfAxtQyQZbwTXVNAHmUpE3B2tFKouQ-n8',
    appId: '1:294025925697:ios:37f77bdbe274d4dc1a62c0',
    messagingSenderId: '294025925697',
    projectId: 'civictrack-b98b3',
    storageBucket: 'civictrack-b98b3.firebasestorage.app',
    iosClientId:
        '294025925697-l10pi5bc5c0pc332noc4j3dk0ion59e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfAxtQyQZbwTXVNAHmUpE3B2tFKouQ-n8',
    appId: '1:294025925697:ios:37f77bdbe274d4dc1a62c0',
    messagingSenderId: '294025925697',
    projectId: 'civictrack-b98b3',
    storageBucket: 'civictrack-b98b3.firebasestorage.app',
    iosClientId:
        '294025925697-l10pi5bc5c0pc332noc4j3dk0ion59e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl4K-N5izYksBUpDtEX_MNvgefJCGHGHU',
    appId: '1:294025925697:web:2db6e6c187af758e1a62c0',
    messagingSenderId: '294025925697',
    projectId: 'civictrack-b98b3',
    authDomain: 'civictrack-b98b3.firebaseapp.com',
    storageBucket: 'civictrack-b98b3.firebasestorage.app',
    measurementId: 'G-GHF4X8JYJR',
  );
}
