// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl4K-N5izYksBUpDtEX_MNvgefJCGHGHU',
    appId: '1:294025925697:web:8b467269b78a52b81a62c0',
    messagingSenderId: '294025925697',
    projectId: 'civictrack-b98b3',
    authDomain: 'civictrack-b98b3.firebaseapp.com',
    storageBucket: 'civictrack-b98b3.firebasestorage.app',
    measurementId: 'G-VFC37ELXW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBGNadpwElTAtiEgTyeZ2eR-qFV41lei8',
    appId: '1:294025925697:android:787d0e2b876e8d181a62c0',
    messagingSenderId: '294025925697',
    projectId: 'civictrack-b98b3',
    storageBucket: 'civictrack-b98b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfAxtQyQZbwTXVNAHmUpE3B2tFKouQ-n8',
    appId: '1:294025925697:ios:37f77bdbe274d4dc1a62c0',
    messagingSenderId: '294025925697',
    projectId: 'civictrack-b98b3',
    storageBucket: 'civictrack-b98b3.firebasestorage.app',
    iosClientId: '294025925697-l10pi5bc5c0pc332noc4j3dk0ion59e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfAxtQyQZbwTXVNAHmUpE3B2tFKouQ-n8',
    appId: '1:294025925697:ios:37f77bdbe274d4dc1a62c0',
    messagingSenderId: '294025925697',
    projectId: 'civictrack-b98b3',
    storageBucket: 'civictrack-b98b3.firebasestorage.app',
    iosClientId: '294025925697-l10pi5bc5c0pc332noc4j3dk0ion59e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl4K-N5izYksBUpDtEX_MNvgefJCGHGHU',
    appId: '1:294025925697:web:2db6e6c187af758e1a62c0',
    messagingSenderId: '294025925697',
    projectId: 'civictrack-b98b3',
    authDomain: 'civictrack-b98b3.firebaseapp.com',
    storageBucket: 'civictrack-b98b3.firebasestorage.app',
    measurementId: 'G-GHF4X8JYJR',
  );
}
